debug: 1                    # Range 0-4 (0 means no debug statements will print)
config_on_startup: false
device: /dev/ttyACM0
frame_id: m8u

inf:
  all: true
  error: true
  warning: true
  debug: false
  notice: false
  test: false

publish:
  all: false
  esf:
    all: true
  hnr:
    pvt: true
  nav:
    pvt: true
    status: true
    att: true
